# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "essentialmix_threading"
description = "essentialmix_threading is a Rust library that has some basic utility functions and components."
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
essentialmix_core = { workspace = true }
async-openai = { version = "0", optional = true }
backoff = "0"
backtrace = "0"
bcrypt = "0"
chrono = "0"
crossbeam = { version = "0", optional = true }
crossterm = "0"
csv = "1"
dialoguer = "0"
dirs = "6"
dotenv = "0"
execute = "0"
fake = { version = "4", features = ["derive", "uuid", "always-true-rng", "random_color", "chrono", "time", "http", "geo", "email_address"] }
file-rotate = { version = "0", optional = true }
fs_extra = "1"
futures = "0"
futures-util = "0"
glob = "0"
html-entities = { version = "0", optional = true }
http-body-util = "0"
image = { version = "0.24.9", optional = true } # compatibility with Kalosm
indicatif = "0"
kalosm = { version = "0", features = ["bert", "llama", "anthropic", "openai", "remote"], optional = true }
kalosm-language = { version = "0", features = ["bert", "llama", "anthropic", "openai", "remote"], optional = true }
lazy_static = "1"
lettre = { version = "0", optional = true }
log = "0"
log4rs = { version = "1", optional = true }
num_cpus = "1"
rand = "0"
randua = "0"
rayon = { version = "1", optional = true }
regex = "1"
reqwest = { version = "0", features = ["blocking", "cookies", "http2", "json", "gzip", "deflate", "brotli", "zstd", "multipart", "socks", "stream"] }
rodio = { version = "0", optional = true }
rpassword = "7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
slog = { version = "2", optional = true }
slog-async = { version = "2", optional = true }
slog-json = { version = "2", optional = true }
slog-scope = { version = "4", optional = true }
slog-stdlog = { version = "4", optional = true }
slog-term = { version = "2", optional = true }
thiserror = "2"
time = "0"
tokio = { version = "1", features = ["full"] }
url = { version = "2", features = ["serde"] }
urlencoding = "2"
uuid = { version = "1", features = ["v4", "serde"] }

[package.metadata.scripts]
run = "cargo run"
check = "cargo check"
build = "cargo build"
release = "cargo build --release"
features = "cargo tree --features"
